-- SCRIPT TO PERFORM DBA RELATED STEPS
-- CONNECT TO tst Database and create schema
CREATE SCHEMA tst;
ALTER SCHEMA tst OWNER TO omsadmin;
-- CREATE PGLOGICAL EXTENSION
CREATE EXTENSION IF NOT EXISTS pglogical;
GRANT pg_signal_backend to omsadmin;
GRANT USAGE ON SCHEMA PGLOGICAL TO OMSADMIN;

-- CREATE READONLY ACCOUNTS
GRANT USAGE ON SCHEMA tst TO OMSROROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA tst TO OMSROROLE;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA tst TO OMSROROLE;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA tst TO OMSROROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA tst GRANT SELECT ON TABLES TO OMSROROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA tst GRANT EXECUTE ON FUNCTIONS TO OMSROROLE;
