name: PostgreSQL for GitHub Actions

on: 
  pull_request:
    types:
      - closed
    branches: [ main ]

    # It will deploy the changes on specified path
    paths:
      - '.github/workflows/**.yml'

  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - name: 'Az CLI login'
      uses: azure/actions/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
