name: PostgreSQL for GitHub Actions

on: 
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: 'Az CLI login'
      uses: azure/actions/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
